---
title: "Introduction to relational databases"
subtitle: "Best Practices in Environmental Data Science<br>FISH 549"
author: "Jennifer Scheuerell"
date: "24 February 2025"
output:
  ioslides_presentation:
    widescreen: true
    css: ["lecture_slides.css", "lecture_inst.css"]
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center", out.width = '90%')
```

## Jennifer Scheuerell

**Education**

* BS, Forestry, University of Washington

* MS, Aquatic and Fishery Sciences, University of Washington

**Appointments**

* Database Specialist, [UW Alaska Salmon Program](https://alaskasalmonprogram.org/) (2004-2007)

* Founder, [Sound Data Management](https://www.sound-data.com/) (2008-present)

* Co-founder, [Sharper Informatics Solutions](https://www.sharperinfo.com/) (2020-present)

* Founding Board Member, [Sound Data Science](https://www.sound-data-science.org/) (2023-present)


## Relational databases | Definition

* a relational database organizes data into tables comprising<br>rows and columns

> * related information is contained in either the same table _or_<br>across multiple tables


## High level concepts

Relational databases are created and manipulated using _Structured Query Language_ (SQL)


## High level concepts

Relational databases are created and manipulated using _Structured Query Language_ (SQL)

_Relational database management systems_ allow users to create relational databases using SQL

Some well known systems include:

* PostgreSQL  
* MySQL  
* Oracle  
* Microsoft SQL Server


## An aside on MS Access

* proprietary software $(\$\$\$)$

> * will only run on Windows OS

> * modest size limits

> * cannot be hosted securely online


## Organizing data in tables

Relational databases store data in tables

> - Columns in a table are fixed *fields*

> - Fields have unique _data types_ (eg, `INTEGER`, `TEXT`)

> - Rows are unique *records*

> - Columns have a fixed order in each table, but SQL does not guarantee the order of the rows within a table


## An example table

| record_ID | color | smell | count | last_updated |
|----------|:-----:|:-----:|:-----:|:------------:|
| record_one | green | pine  | 13 | 2024-02-17 | 
| record_two | yellow | lemon | 20 | 2024-12-13 | 
| record_three | red | cherry | 5 | 2025-02-19 | 


## Same table again

| record_ID | color | smell | count | last_updated |
|----------|:-----:|:-----:|:-----:|:------------:|
| record_three | red | cherry | 5 | 2025-02-19 | 
| record_one | green | pine  | 13 | 2024-02-17 | 
| record_two | yellow | lemon | 20 | 2024-12-13 | 


## Jargon | Primary and foreign keys  

a _primary key_ is one (or more) field(s) in a table that uniquely identifies each record in the table


## Jargon | Primary and foreign keys  

a _primary key_ is one (or more) field(s) in a table that uniquely identifies each record in the table

<br>

a _foreign key_ is a field in a table that joins to a field in a second table


## Jargon | Joins  

a _join_ brings together two tables using one or more fields they share in common 


## An example join {data-background=images/simple_example_join.png data-background-size=75% data-background-position=50%50%}


## Jargon | Atomic values  

an _atomic value_ is a singular piece of information


## Jargon | Atomic values  

an _atomic value_ is a singular piece of information

<br>
 
**NOTE**: relational databases expect only one piece of information to be stored in any one field within a record


## Example table with non-atomic values

| record_ID | date | site | wind_speed_direction |
|----------|:-----:|:-----:|:-----:|
| record_one | 2024-06-02 | Madison Park | 10N |
| record_two | 2024-06-02 | Magnuson Pt | 13NE |
| record_three | 2024-06-02 | St Edwards | 7E |


## Jargon | Null values  

a _null value_ is used to denote that the information for that field for that record is missing


## Jargon | Null values  

a _null value_ is used to denote that the information for that field for that record is missing

<br>

**NOTE**: in **R** this is an `NA`


## Jargon | Select query & result set  

a _select query_ is a SQL statement that extracts data from one or more tables


## Jargon | Select query & result set  

a _select query_ is a SQL statement that extracts data from one or more tables

<br>

a _result set_ is the data that are returned by the `select query` statement 


## Jargon | View  

a _view_ is a saved `select query`

<br>

**NOTE**: only the SQL statement is saved, not the result set from running the query


## Jargon | View  

a _view_ is a saved `select query`

<br>

**NOTE**: only the SQL statement is saved, not the result set from running the query

<br>

A _view_ is to SQL as a _script_ is to R


## Tables in databases

* 2+ tables are grouped into databases

> * multiple databases within a server constitute a *database cluster*


## Designing a database {data-background=images/data_model.png data-background-size=71% data-background-position=32%58%}


## Designing a database {data-background=images/data_model_plus_table.png data-background-size=85% data-background-position=63%57%}


## Data Normalization | Third Normal Form

"[every] non-key [attribute] must provide a fact about the key, the whole key, and nothing but the key, so help me Codd."


## Next time

* connect to a remote database via **RStudio**

* view tables

* write a simple query

