---
title: "Creating a global `.gitignore` file"
output:
  html_document:
    theme: spacelab
    highlight: textmate
    css: ["lecture_inst.css", "fontawesome.css", "solid.css"]
    toc: true
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# What is a `.gitignore` file?

As its name might suggest, a `.gitignore` file specifies folders or files that Git should intentionally ignore (i.e., leave "untracked"). Each line in the `.gitignore` files specifies a folder, filename, or patterns to be matched against folders or filenames. Here are some of things to note about characters and patterns in `.gitignore` file (you can find more details [here](https://git-scm.com/docs/gitignore)).

* Any line or string beginning with `#` is considered a comment. If you want to match a literal `#`, precede it with a backslash (i.e., `\#`).

* A blank line won't match anything, so you can use it to separate other lines or blocks of code and improve readability.

* Trailing spaces are ignored unless they are preceded by a backslash (e.g., `\  `).

* Use a forward slash `/` to separate directories.

    - A `/` may occur at the beginning, middle or end of the `.gitignore` search pattern.

    - If there is a `/` at the beginning or middle (or both) of the pattern, then the pattern is relative to the folder/directory level of the particular `.gitignore` file itself.

    - If there is a `/` at the end of the pattern, the pattern will only match folders/directories, otherwise the pattern can match both files and folders/directories
    
    - All paths are relative to the location of the `.gitignore` file (e.g., `data/science/` matches the `data/science` directory, but not the `x/data/science` directory_.

* An asterisk `*` is a wild card that matches anything except a forward slash `/` (e.g., `data/*` would ignore everything in the data folder). The question mark `?` matches any _single_ character except a forward slash `/`.

***

# Why use a `.gitignore` file?

There are several reasons you might use a `.gitignore` file. At a philosophical level, your workflow should really include only the files and accompanying instructions or code necessary to reproduce the specific analysis. For example, operating systems may leave esoteric files behind that don't have any influence on the inputs or outputs of the analysis, nor would they matter to a different OS (see below). At a more practical level, you might not need to track the `.html` files generated by a `.Rmd` file if they were not part of a rendered website. Or, you might have very large data files that are updated and shared with your team members via different means.

***

# How to use a `.gitignore` file?

When you place a folder/directory under version control via Git (e.g., `git init`), Git does not automatically create a `.gitignore` file so you have to do so manually. In general, the exclusions you include in any `.gitignore` file should be specific to the project and its associated folders/directories and files. When you create a new repo in GitHub, you have the option of creating a `.gitignore` file based upon a variety of templates for common project or coding types (e.g., R, Python).


